### ISSUE TITLE
I scale the SVG > 1.0 but the image buffer dimensions is not scaled accordingly.

### ISSUE THREAD

**Issue by shaovoon** [svgpp/svgpp#103]
Hi, thanks for this wonderful SVG library. I have encountered an issue with a transform in the svgpp_gdip_render_msxml sample. I hope you can spare a little of your precious time to help me.

```Cpp
void renderDocument(XMLDocument & xmlDocument, ImageBuffer & buffer, double scale)
{
  Document document(xmlDocument);
  Canvas canvas(document, buffer);
  boost::array<number_t, 6> matrix{scale, 0.0, 0.0, scale, 1.0f, 1.0f}; // I added this line
  canvas.transform_matrix(matrix); // I added this line
  document_traversal_main::load_document(xmlDocument.getRoot(), canvas);
}
```

The SVG is scaled accordingly but the image buffer dimensions are not scaled accordingly, resulting in the image being cut off. Is there a way to scale the image size?

**Comment by svgpp** [comment]
Hi, you may try to take scale into account when setting ImageBuffer size (
https://github.com/svgpp/svgpp/blob/1578464a5b2843735b00c1d708ac2a075081c541/src/demo/render/svgpp_render.cpp#L592).
I'm not sure that it's the best way, but something like this should work.


вт, 5 июл. 2022 г., 09:35 shaovoon ***@***.***>:

**Comment by shaovoon** [comment]
Thanks! I added a `dpi_scale_` member to the `Canvas` class and set it according to DPI. It works perfectly. Thanks again.
