### ISSUE TITLE
Q: not processing root <svg> element?

### ISSUE THREAD

**Issue by mawnlower** [svgpp/svgpp#104]
Sorry, noob question: with code like this (mine)
```c++
rapidxml_ns::xml_document<> doc;
doc.parse<0>("imagine well-formed, valid SVG XML here");

if (rapidxml_ns::xml_node<> * root = doc.first_node("svg"); root != nullptr)
{
  svgpp::document_traversal <
    svgpp::processed_elements<processed_elements_t>,
    svgpp::processed_attributes<svgpp::traits::shapes_attributes_by_element>,
    svgpp::error_policy<smart_error_policy>
  >::load_document(root, adapter);
}
```
where: `adapter` is the object receiving the callbacks (ofc)

svgpp never calls back to `adapter::on_enter_element(tag::element::svg)`
The first callback I get is for the first element _within_ `<svg>`.

Is this expected behaviour?
Should I parse any attributes on the root node just using rapidxml_ns::xml_node?

I would prefer to be called back on the root node.
Then all the processing is homogenous code.

Can I do things differently to bring this about ?

**Comment by magjac** [comment]
This is the expected behavior. See https://github.com/svgpp/svgpp/issues/98#issuecomment-866674733.
