### ISSUE TITLE
Callbacks when loading a <use> element?

### ISSUE THREAD

**Issue by mawnlower** [svgpp/svgpp#108]
I am following the [tutorial](https://www.svgpp.org/lesson01.html#the-use-element-support) for resolving `<use>` elements in SVG.

I think I have adequately filled in the blanks that this tutorial leaves for the reader, such as locating the referenced XML element, cloning this element and augmenting it with the attributes from the `<use>` element.

I am now ready to load this cloned element:
```c++
// variable "element" below is the referred-to element
// which I have located in my XML document.

auto clone = doc->clone_node(element);
// add or overwrite x, y, width and height attributes on this clone
...
document_traversal_t::load_referenced_element<
      referencing_element<tag::element::use_>,
      expected_elements<traits::reusable_elements>,
      processed_elements<
        boost::mpl::insert<processed_elements_t, tag::element::symbol>::type 
      >
    >::load(clone, *this);
 ```
What would I expect to happen now?
How can I test that the tutorial code now works?

Using the XML used in your tutorial, I would expect the context to receive callbacks for attributes x, y, width and height.
I think I have properly added these to the `BaseContext` in your tutorial, but I just don't seem to receive them.

**Comment by svgpp** [comment]
Probably the demo app may give you better understanding of how to handle `<use>` elements.
https://github.com/svgpp/svgpp/blob/b9f31c10af569c2262c277d89d084dc743e17878/src/demo/render/svgpp_render.cpp#L923
As you can see, x, y, width, height are processed on `<use>` element itself to adjust current transform.

**Comment by mawnlower** [comment]
Actually, I think I did a bad job in asking my question clearly. Let me try a different way.

This is the XML from the linked tutorial:
```xml
<svg width="10cm" height="3cm" viewBox="0 0 100 30" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <defs>
    <rect id="MyRect" width="60" height="10"/>
  </defs>
  <rect x=".1" y=".1" width="99.8" height="29.8"/>
  <use x="20" y="10" xlink:href="#MyRect"/>
</svg>
```
Upon calling `document_traversal_t::load()` using the cloned node (that is based on the above `MyRect` template) can I expect a callback to my code with the rectangle `[x=20, y=10, width=60, height=10]` ?

Perhaps I am suffering from snow-blindness in the face of so much templated code, but I cannot work out how my context handler receives the rectangle.

I am suggesting that perhaps the example code does not close this loop by proving that the context will receive a `tag::element::rect` as the nett result of resolving the `use` element.

If it does do this, can you point at the line in the code where the callback occurs?
Ideally for both the [original tutorial](https://www.svgpp.org/lesson01.html#the-use-element-support) and maybe also for the other demo you linked to?
