### ISSUE TITLE
Incorrect handling of transform in svg path

### ISSUE THREAD

**Issue by sheetcam** [svgpp/svgpp#110]
When using a path with transformation the transformation is applied after the path is drawn.
To demonstrate the issue use sample01b.cpp with the following SVG:

    TEXT(<svg xmlns="http://www.w3.org/2000/svg">)
    TEXT(<path d="M 80 80 A 45 45, 0, 0, 0, 125 125 L 125 80 Z" transform="scale(1.5)" />)
    TEXT(</svg>);

The resultant call sequence is:
path_move_to
path_elliptical_arc_to
path_line_to
path_close_subpath
transform_matrix

When using that sample with it's original ellipse SVG the call sequence is as expected:
transform_matrix
path_move_to
path_elliptical_arc_to
path_elliptical_arc_to
path_close_subpath

This is with Git master, compiled with Visual Studio 2019.

**Comment by svgpp** [comment]
This is not an error. By default the library will parse (and pass values of) attributes one-by-one in the written order. So we usually do painting in `on_exit_element`, it is most convenient in many cases.  But you may also check [Attribute Traversal Policy](https://svgpp.org/document_traversal.html#attribute-traversal-policy) - it has `get_deferred_attributes_by_element` especially for cases like yours, when you want attribute values to come in some specific order. Also see comment [here](https://github.com/svgpp/svgpp/blob/536233cbf232c26a5a2d532b63b2c9ab7338bdc0/include/svgpp/policy/attribute_traversal.hpp#L34).
