### ISSUE TITLE
Problems with Boost macro resolution

### ISSUE THREAD

**Issue by Desperado17** [svgpp/svgpp#125]
Trying to build master with clang-17 and boost 1.84 on an x64 Ubuntu Linux.  There seem to be problems with macro resolution:

/media/user/SSD1TB/Project8/dev/dist/libs/svgpp-dev/4/workspace/usr/include/svgpp/definitions.hpp:99:5: error: expected ',' or '>' in template-parameter-list
   99 |     BOOST_PP_ENUM_BINARY_PARAMS(SVGPP_TYPE_OR_LITERAL_ARITY, class Value, = boost::mpl::na BOOST_PP_INTERCEPT)> 
      |     ^
/media/user/SSD1TB/Project8/dev/dist/system/boost-dev/6/workspace/usr/include/boost/preprocessor/repetition/enum_binary_params.hpp:25:79: note: expanded from macro 'BOOST_PP_ENUM_BINARY_PARAMS'
   25 | #    define BOOST_PP_ENUM_BINARY_PARAMS(count, p1, p2) BOOST_PP_REPEAT(count, BOOST_PP_ENUM_BINARY_PARAMS_M, (p1, p2))
      |                                                                               ^

In file included from /media/user/SSD1TB/Project8/dev/dist/libs/svgpp-dev/4/workspace/usr/include/svgpp/policy/xml/rapidxml_ns.hpp:12:
/media/user/SSD1TB/Project8/dev/dist/libs/svgpp-dev/4/workspace/usr/include/svgpp/definitions.hpp:99:5: error: expected unqualified-id
/media/user/SSD1TB/Project8/dev/dist/system/boost-dev/6/workspace/usr/include/boost/preprocessor/repetition/enum_binary_params.hpp:25:79: note: expanded from macro 'BOOST_PP_ENUM_BINARY_PARAMS'
   25 | #    define BOOST_PP_ENUM_BINARY_PARAMS(count, p1, p2) BOOST_PP_REPEAT(count, BOOST_PP_ENUM_BINARY_PARAMS_M, (p1, p2))

Any ideas?  Reagards

**Comment by Desperado17** [comment]
It seems to me that BOOST_PP_INTERCEPT is not defined. Might be because 
#include <boost/preprocessor/facilities/intercept.hpp>
is not included directly in definitions.hpp.

**Comment by svgpp** [comment]
1. What were the changes from the last successful build?
2. Does it help get #include <boost/preprocessor/facilities/intercept.hpp> in definitions.hpp?

**Comment by Desperado17** [comment]
I only built it with gcc so far. Now I'm making attempts with clang-17. And boost was upgraded from 1.65 to 1.84.
Including intercept.hpp solves that particular problem although there are more.


Edit: I have here a template instantiation that suddenly has an int & parameter where I think it wasn't before. All the set implementations from our Context implementation don't fit anymore. Any idea what that might be?

value_events.hpp:23:13: error: no matching member function for call to 'set'
   23 |     context.set(tag, args...);
      |     ~~~~~~~~^~~
<...>
/media/user/SSD1TB/Project8/dev/dist/libs/svgpp-dev/4/workspace/usr/include/svgpp/parser/paint.hpp:99:47: note: in instantiation of function template specialization
'svgpp::detail::pass_iri_value_proxy<svgpp::policy::value_events::default_policy<MyContext>>::set<MyContext, svgpp::tag::attribute::fill, svgpp::tag::source::css, boost::iterator_range<const char *>, int &, svgpp::tag::skip_icc_color &>' requested here
   99 |               value_events_with_iri_policy_t::set(value_events_context, tag, property_source, iri, color.template get<0>(), *color.template get<1>());

**Comment by svgpp** [comment]
<boost/preprocessor/facilities/intercept.hpp> should already be included in definitions.hpp throw this include chain:
<svgpp/utility/boost_parameter_fixed.hpp> ->
<exboost/parameter.hpp> ->
<exboost/parameter/parameters.hpp> ->
<boost/preprocessor/facilities/intercept.hpp>

Please share your findings

**Comment by Desperado17** [comment]
After clearing all of my caches it now suddenly built to the end. Sorry to have bothered you.
