### ISSUE TITLE
Error reading file Reinel_compass_rose.svg in element path

### ISSUE THREAD

**Issue by sakrist** [svgpp/svgpp#32]
Tried render Reinel_compass_rose.svg with svgpp_agg_render example.

Error reading file Reinel_compass_rose.svg in element "path": Invalid value of SVG attribute (or property) "d": "M0 h94 m9 h49 m12 h51"

http://upload.wikimedia.org/wikipedia/commons/e/eb/Reinel_compass_rose.svg

**Comment by svgpp** [comment]
"m" path command requires pair of coordinates after it. So there is an error in the SVG document. SVG Specification says "The document shall be rendered up to, but not including, the first element which has an error". Therefore current behavior is correct, it will be better to fix SVG document.
If you want to continue rendering document in case of errors, you should inherit your class from svgpp::policy::error::raise_exception, override its parse_failed method to not throw exception, but return "true" instead, and pass this new class as template parameter svgpp::error_policy<new_error_policy_class> to document_traversal class.

**Comment by sakrist** [comment]
Something like this?:
```
template<class Context>
struct custom_error_policy: svgpp::policy::error::raise_exception<Context>
{
    template<class AttributeTag, class AttributeValue>
    static bool parse_failed(Context const &, AttributeTag,
                             AttributeValue const & value)
    {
        return true;
    }
};
```

And `error_policy<custom_error_policy>` in document_traversal?

Was trying it and got compiling error, `/Users/sakrist/Documents/Work/CircumLunar/CircumLunar/Classes/SVG/cpp/CLSVGPP.cpp:424:22: Use of class template 'custom_error_policy' requires template arguments`.
Now sure how to resolve it. 

Thank you

**Comment by svgpp** [comment]
If all your contexts have common base, let's say BaseContext:

```c++
struct custom_error_policy: svgpp::policy::error::raise_exception<BaseContext>
{
    template<class AttributeTag, class AttributeValue>
    static bool parse_failed(BaseContext const &, AttributeTag,
                             AttributeValue const & value)
    {
        return true;
    }
};
```

**Comment by svgpp** [comment]
Increase BOOST_PARAMETER_MAX_ARITY value. Not sure what is default value. Try something like
```c
#define BOOST_PARAMETER_MAX_ARITY 15
```
before any other include

**Comment by sakrist** [comment]
Thanks! 
That will be nice add to documentation.
