### ISSUE TITLE
Incorrect marker viewport handling

### ISSUE THREAD

**Issue by gcampax** [svgpp/svgpp#34]
According to the SVG 1.1 specification, section 11.6.2, the attributes refX / refY on marker elements are defined as coordinates in the coordinate system after applying viewBox and preserveAspectRatio.
Unfortunately SVG++ resolves the refX / refY value before computing the viewBox, which means that percentage values for refX / refY will be incorrect.

**Comment by svgpp** [comment]
1. By default SVG++ passes attribute values in "raw" order - as they are in XML. It is ok for DOM constructing, but may be inconvenient for immediate processing.
2. Order of attributes processing may be changed manually by [Attribute Traversal Policy](http://svgpp.org/document_traversal.html#attribute-traversal-policy).
3. And the most convenient way is to use automatic viewport processing for markers with [Viewport Policy](http://svgpp.org/viewport.html). In this case refX, refY, markerWidth, markerHeight, viewBox
 and preserveAspectRatio attributes are processed inside SVG++, passing ready to use transform and viewport size to the program.
Is this helps you?

**Comment by gcampax** [comment]
That is unfortunately not what I meant.
I was referring specifically to the code in the marker_viewport.http calculate_marker_viewport_adapter::on_exit_attributes - that code processes refX / refY before viewbox and that is wrong according to the SVG specification - causing svgpp to pass wrong values as transform and viewport size

**Comment by svgpp** [comment]
Now I see. Looks like an actual bug in the library. I'll check. Thank you
