### ISSUE TITLE
Call to 'ref' is ambiguous - xcode C++ collision

### ISSUE THREAD

**Issue by jbuck167** [svgpp/svgpp#43]
Fresh download, trying to compile [https://github.com/svgpp/svgpp/blob/master/src/samples/sample01b.cpp](https://github.com/svgpp/svgpp/blob/master/src/samples/sample01b.cpp)

In file "number.hpp" I get an ambiguous call to the second 'ref' on line 108
`>> number [ref(value2) = _1, ref(two_values) = true]`
and
In file "misc.hpp" I get the ambiguous call to the second 'ref' on line 188
`if (qi::parse(it, end, number[ref(value) = _1] >> -(qi::lit('%')[ref(percentage) = true])) && it == end)`

In both cases, the collision type is bool and there are two candidate functions, one in "__functional_base.cpp" and one in "reference.hpp". It seems pretty clear that the intended usage is the definition in "reference.hpp". 

The problem seems to be Xcode Specific because "__functional_base.cpp" is part of the default xcode C++ toolchain.

**Comment by jbuck167** [comment]
If anyone else does encounter this problem because they like xcode, I fixed it by duplicating the definition of 'ref' in file "reference.hpp" and named the copy 'refcpy'. I then renamed the ambiguous calls to 'ref' to 'refcpy'.

**Comment by svgpp** [comment]
Could you please try to specify exact namespace boost::phoenix::ref? It would be much more reliable fix if it works.

**Comment by jbuck167** [comment]
Thanks for providing the correct namespace. It appears that boost::phoenix::ref is the correct namespace and using that namespace worked for me.
