### ISSUE TITLE
I have a problem to draw shape.

### ISSUE THREAD

**Issue by Fogrunner** [svgpp/svgpp#45]
I tried to draw svg path data to gdi+ bitmap. I referred to source code in demo for completing it. 

In result :

1) It is a svg path of `dash `character and works well. (It consists of lines)

`<path d="M616 440H66V621H616V440Z"/>`

2)  It is a svg path of `alphabet O `character and does not work. (It consists of curves)

`<path d="M569 1085q215 0 356.5 -140T1067 547Q1067 234 914 104.5T569 -25Q368 -25 220 108T72 530q0 280 143 417.5T569 1085ZM569 123q154 0 234 114t80 300q0 199 -90.5 300T569 938Q432 938 344 835.5T256 530q0 -202 89.5 -304.5T569 123Z"/>`

Case number 2, nothing rendered. The paths which contain Bezier curve seem not to work. 

I made `Context ` the same as `PathStorage `in demo source code. 

I have almost spent 5 days to fix it.

Please help me, give me some piece of advice.

**Comment by svgpp** [comment]
Unfortunately, you stumble on library bug. Please have a look onto the last commit that fixes library and GDI+ demo code.

**Comment by Fogrunner** [comment]
Oh!

That's why...

I  will apply the new version and let you know the results.

Thank you for fixing. 👍

**Comment by Fogrunner** [comment]
I have tested with some svg paths of the other characters.

It is work perfectly.

thank you so much! nice!
