### ISSUE TITLE
There are some problem with gdiplus. 

### ISSUE THREAD

**Issue by Fogrunner** [svgpp/svgpp#46]
Hello. It is me again.

I have encountered a new problem with gdiplus.

I tried to draw a svgpath.

> M688 564Q631 523 555 487q56 -17 121.5 -31.5T804 432q8 -1 9.5 -4.5T813 417l-9 -34q-2 -11 -16 -8q-32 5 -71.5 13t-82 18t-85 21.5T468 450Q397 422 318 400.5T156 365q-15 -3 -19 7l-12 34q-2 5 1 9.5t9 6.5q70 14 132 30.5t118.5 35t109 41T599 577q17 9 15.5 15.5T597 599H199q-13 0 -13 13v35q0 12 13 12H631q78 0 95 -27.5T688 564ZM900 277t5 -3.5t5 -9.5V230q0 -5 -5 -9t-10 -4H45q-6 0 -10.5 4T30 230v34q0 6 4.5 9.5T45 277H432V383q0 14 14 14h41q14 0 14 -14V277H895q5 0 10 -3.5ZM502 158q-1 -5 -1 -10t-1 -10q3 -14 9 -26T523 89Q561 31 639.5 -13T827 -79q6 -2 7 -7t-1 -10l-16 -33q-2 -5 -5.5 -7.5T798 -137q-116 27 -201.5 78T469 57Q431 -6 350.5 -58T149 -143q-16 -4 -20 5l-14 37q-2 5 -0.5 11t8.5 8Q275 -41 354 22.5T436 161q0 12 12 12l46 -1q9 0 8 -14ZM611 782t0 -14V736q0 -15 -15 -15H333q-15 0 -15 15v32q0 14 15 14H596q15 0 15 -14Z

i could draw it correctly with FillPath method of gdiplus.

![2](https://cloud.githubusercontent.com/assets/11848318/21169377/ee8461e6-c1fe-11e6-86e4-5df58fb7251b.png)

But, in case of DrawPath method. There was some artifacts like below.

![default](https://cloud.githubusercontent.com/assets/11848318/21169342/a9550fee-c1fe-11e6-9214-99c267f379dd.png)

I painted red rectangles on the artifacts.

Please help me.

**Comment by svgpp** [comment]
Hi,

Please create SVG sample that reproduces such artifacts with svgpp_gdip_render_msxml sample from SVG++.

**Comment by Fogrunner** [comment]
Hi. Thank you for replying.

I will make the SVG sample VS2015, Win32 Application.

Is it fine?

ps, Where can i get the code called svgpp_gdip_render_msxml?

**Comment by svgpp** [comment]
Hi,

I mean that "svgpp" solution that is generated by CMake (from svgpp/src/CMakeLists.txt) already contains svgpp_gdip_render_msxml project, it is SVG++ demo application with GDI+ and MSXML options. You should be using its code as a base for your implementation. svgpp_gdip_render_msxml utility renders SVG file passed to it on command line to PNG. It'll be helpful to get from you just the SVG file which will produce same artifacats in PNG when processed by svgpp_gdip_render_msxml.

**Comment by Fogrunner** [comment]
I have tested it with your svgpp_gdip_render_msxml as you said. 
And i could find the reason of why. 

Those artifacts turned out that it is related to SetLineJoin functionality.

If i do not use SetLineJoin, SetMiterLimit methods, i could see the artifacts.
![image](https://cloud.githubusercontent.com/assets/11848318/21283555/a66f9dc6-c447-11e6-81ff-ab7073d66305.png)


If i use both, the artifacts are gone as like below.
![image](https://cloud.githubusercontent.com/assets/11848318/21283538/57712faa-c447-11e6-99d8-216e5df452e4.png)


![image](https://cloud.githubusercontent.com/assets/11848318/21283620/dc070ee6-c448-11e6-8f89-1f0baa05be2e.png)

I marked origins of the artifacts with blue rectangles on above picture.
The points might be connecting point of each shapes. 

I am not sure whether it is related to parser's approximation of floating or the asset problem. 

It is full text of the asset.

> <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 2000 2000">
>   <path stroke="red" stroke-width="1" d="M688 564Q631 523 555 487q56 -17 121.5 -31.5T804 432q8 -1 9.5 -4.5T813 417l-9 -34q-2 -11 -16 -8q-32 5 -71.5 13t-82 18t-85 21.5T468 450Q397 422 318 400.5T156 365q-15 -3 -19 7l-12 34q-2 5 1 9.5t9 6.5q70 14 132 30.5t118.5 35t109 41T599 577q17 9 15.5 15.5T597 599H199q-13 0 -13 13v35q0 12 13 12H631q78 0 95 -27.5T688 564ZM900 277t5 -3.5t5 -9.5V230q0 -5 -5 -9t-10 -4H45q-6 0 -10.5 4T30 230v34q0 6 4.5 9.5T45 277H432V383q0 14 14 14h41q14 0 14 -14V277H895q5 0 10 -3.5ZM502 158q-1 -5 -1 -10t-1 -10q3 -14 9 -26T523 89Q561 31 639.5 -13T827 -79q6 -2 7 -7t-1 -10l-16 -33q-2 -5 -5.5 -7.5T798 -137q-116 27 -201.5 78T469 57Q431 -6 350.5 -58T149 -143q-16 -4 -20 5l-14 37q-2 5 -0.5 11t8.5 8Q275 -41 354 22.5T436 161q0 12 12 12l46 -1q9 0 8 -14ZM611 782t0 -14V736q0 -15 -15 -15H333q-15 0 -15 15v32q0 14 15 14H596q15 0 15 -14Z"/>
> </svg>
> 

By the way, i can resolve this problem with Gdiplus::LineJoinMiterClipped and Miterlimit.

Thank you for helping. Sincerely.
