### ISSUE TITLE
在MFC中使用svgpp报错：error C3861: “min”: 找不到标识符

### ISSUE THREAD

**Issue by geekmingl** [svgpp/svgpp#47]
您好，感谢您百忙之中查看该信息。
我在一个MFC工程中使用svgpp，在project中增加 NOMINMAX 。编译之后报错：
1>c:\program files (x86)\windows kits\8.1\include\um\gdiplustypes.h(475): error C3861: “min”: 找不到标识符
不知道怎么解决，请大神帮忙看看，谢谢！

**Comment by svgpp** [comment]
Hi,

Googling for "gdiplustypes.h(475) min" gives pretty reasonable answer at http://stackoverflow.com/questions/15900381/nominmax-with-visual-studio-2012-mfc-project

**Comment by geekmingl** [comment]
您好，感谢您能认真的给我解答。
我尝试着按照上面的方法做。在我的文件（QrCode.cpp）中
将
`#include <algorithm>`
改成
```
#define NOMINMAX
#include <algorithm>
namespace Gdiplus
{
	using std::min;
	using std::max;
};
```
但是仍然会提示上述错误。

**Comment by svgpp** [comment]
Are you sure that this "using ..." comes before GDI+ headers? Better to place entire fragment 
```#define NOMINMAX
#include <algorithm>
namespace Gdiplus
{
	using std::min;
	using std::max;
};
```

at first lines of QrCode.cpp

**Comment by geekmingl** [comment]
您好，我在stdafx.h的第一行添加了：
`#define NOMINMAX`
在QrCode.cpp最上面增加：
`#include <algorithm>
namespace Gdiplus
{
	using std::min;
	using std::max;
};`
在TEST_QRDlg.cpp种包含了头文件。

我将我的源码上传到了git：https://github.com/geekmingl/TEST_QRCODE.git
非常抱歉打扰您，这个问题让我百思不得其解。也非常感谢您能百忙之中给我解答！！！
