### ISSUE TITLE
How to support Intersection clip path?

### ISSUE THREAD

**Issue by tyware** [svgpp/svgpp#50]
The intersection clip path is archived by the attribute "clip-path" of element "ClipPath" with the use element. But it seems like the attribute "clip-path" in element "ClipPath" isn't supported. The below is the sample file:

 

`<defs>`

`<clipPath id="clip1">`
    `<polygon` `id="clip1Shape"` `points="100,10` `40,180` `190,60` `10,60 160,180 100,10" stroke="blue" /> `
`</clipPath>`

`<clipPath id="clip2">`
    `<circle id="clip2Shape" cx="100" cy="100" r="65" />`
`</clipPath>`

`<!-- Intersection -->`
`<clipPath id="clipIntersection" clip-path="url(#clip1)">`
    `<use x="0" y="0" width="200" height="200" xlink:href="#clip2Shape" />`
`</clipPath>`

  `</defs>`

  `<g inkscape:label="Layer 1"   inkscape:groupmode="layer"  id="layer1">`

   `<rect x="10" y="10" width="180" height="180" fill="red" `
       `clip-path="url(#clipIntersection)" transform="translate(200)" />`
       
 `</g>`

**Comment by svgpp** [comment]
You probably mean svgpp_demo application. Yes, such feature is missing there, but it looks not difficult to add support for "clip-path" attribute in ElementBase class in demo/render/clip_buffer.cpp.
