### ISSUE TITLE
Empty SVGs in samples

### ISSUE THREAD

**Issue by osmial** [svgpp/svgpp#61]
I've question regarding samples, actually it's not only about Sample01a but other samples too.
So in main function we have:
char text[] = "< svg / >";
and this text is being used by xml parser which means this is our svg sample, right?
If yes then our hooks methods declared in Context class should be called appropriately, so if I'll add some logging inside them I should observe some actions, but question is if this code "< svg / >" is enough?
It might be obvious but it's not. I'm not seeing any logging even for quite longer code but if I add code to open existing file and run parsing over it I can observe logs.
Can anybody clarify it to me?
Thanks in advance!

**Comment by svgpp** [comment]
You're right, "" isn't valid SVG apparently. It looks like a poor decision to put it in sample. Probably the reason was to make samples as small as possible. I'll think about replacing it with file reading or hardcoded SVG. Thanks.

**Comment by osmial** [comment]
I've updated my comment - please take a look again on it.
The string isn't empty - it's only shown here as empty, probably browser tried to parse it. I've added some spaces in tag to prevent parsing it.
So what if there is a tag actually?

**Comment by svgpp** [comment]
`<svg/>` is valid XML unlike "", but it isn't valid SVG still, because `svg` element is in default XML namespace but is must be in `http://www.w3.org/2000/svg`. So no actual SVG parsing is performed by svgpp.

**Comment by osmial** [comment]
Thanks for your answer. I was testing using examples like those presented here: https://www.w3schools.com/graphics/svg_examples.asp
Maybe there should be a short description somewhere about that?
Or example svg code in samples should contain information about namespace and one additional svg element which will trigger some action after adding logging? For newbies like me it would save a lot of time when they start working with this library.
I can do the changes depending on what option you will choose (if any).
