### ISSUE TITLE
Missing information in documentation?

### ISSUE THREAD

**Issue by osmial** [svgpp/svgpp#62]
When elements like path or other shapes contains 'fill' attribute I want to get this information.
Based on what is written in documentation about set methods I've added:
`document_traversal< processed_attributes<boost::mpl::set<boost::mpl::pair<tag::element::path, tag::attribute::fill>>::type> >::load_document(xml_root_element, context);`
But I can't find out what arguments I should pass to set method.
I've tried multiple options like:
`template<class Range>
 void set(svgpp::tag::attribute::fill, Range const & r)`
and others but it not seems to be good choice.
Compiler tries to help:
include/svgpp/policy/value_events.hpp:23:5: error: no matching function for call to ‘Context::set(svgpp::tag::attribute::fill&, const boost::iterator_range<const char*>&, const int&)’
but when I'm trying to find anything in documentation about that I'm finding nothing.
Am I missing something?
Thanks in advance!

**Comment by svgpp** [comment]
`fill` property has the same type as `stroke` property - `<paint>` described [here](http://svgpp.org/value.html).
So you may just copy code in samples with `tag::attribute::stroke` and rename tag to `tag::attribute::fill`.
Or, usually you may want to have common template class for both `stroke` and `fill` like `PaintContext` in https://github.com/svgpp/svgpp/blob/master/src/demo/render/stylable.hpp

**Comment by osmial** [comment]
Thanks for your answer!
