### ISSUE TITLE
[Demo] auto_ptr throwing a lot of warnings - auto_ptr deprecated

### ISSUE THREAD

**Issue by ghost** [svgpp/svgpp#66]
Hi Oleg,

would it be possible to change **_auto_ptr_** to **_unique_ptr_** or **_shared_ptr_**? auto_ptr is deprecated in later C++ versions or do you need to keep to support older compilers?

Very kind regards!

**Comment by svgpp** [comment]
Hi Hans-J.,
SVG++ library (include/*) doesn't use auto_ptr. Actually, it just doesn't allocate heap at all.
Demo app (src/demo) does reference auto_ptr in a couple of places. 
So the problem isn't critical but should be addressed anyway. Thank you for reporting.

**Comment by schmidh** [comment]
Would it be safe to replace auto_ptr by unique_ptr? It is supposed to be a drop-in replacement. If yes I could do a PR to make your life easier.

**Comment by svgpp** [comment]
It's pretty easy to do, but I haven't decided yet if I should drop C++03 support. Maybe even ugly selection with macros between auto_ptr and unique_ptr will do. I'll think about it.

**Comment by schmidh** [comment]
Maybe here some grains of thought: 

https://softwareengineering.stackexchange.com/questions/291141/how-to-handle-design-changes-for-auto-ptr-deprecation-in-c11
