### ISSUE TITLE
This library can be compiled on the iOS and Android?

### ISSUE THREAD

**Issue by lonshine** [svgpp/svgpp#73]
This library can be compiled on the iOS and Android?
Are there any demo?

**Comment by svgpp** [comment]
I know that some people get SVGPP compiled on Android (e.g. see #56). Never heard about iOS.
I've never done it myself, so can't help with that, sorry.

**Comment by RichardCory** [comment]
I know this question is way old, but Microsoft provides iOS support for SVG using svg++
