### ISSUE TITLE
Double free bug in the third party

### ISSUE THREAD

**Issue by gaintcome** [svgpp/svgpp#74]
I observed a pretty obvious double free bug in `stb.h` file.

https://github.com/svgpp/svgpp/blob/0109a252b7543da89943f2fc9092e2ec77be2cd6/third_party/stb/stb.h#L10054

I'm not even sure you can assign a CVE to it since it's more like a typo :)

Thanks,
Reza

**Comment by svgpp** [comment]
It was already [fixed](https://github.com/nothings/stb/commit/b3653cc3f17a02fe249671624d950d716a4b0806) in STB repo, so I just have to update to latest STB.
