### ISSUE TITLE
Can't Compile using MinGW 

### ISSUE THREAD

**Issue by omortie** [svgpp/svgpp#77]
I'm using:
MinGW (GNU Make 4.2.1)
CMake 3.15.1
Qt 5.12.1
Boost 1.7
for compiling the svgpp but I get the error:
`svgpp/include/svgpp/utility/gil/mask.hpp:32:23: error: 'bits32f' was not declared in this scope
       channel_convert<bits32f>(red  )*0.2125f +`
anybody knows any suggestion why it's happening?

**Comment by svgpp** [comment]
I hope this fix will work, I've never checked it.
