### ISSUE TITLE
too many sections error when compiling src with MinGW

### ISSUE THREAD

**Issue by omortie** [svgpp/svgpp#78]
I tried to compile src folder following instructions but I get this error with MinGW:

`08:45:21: Running steps for project svgpp...
08:45:21: Persisting CMake state...
08:45:24: Starting: "C:\Program Files\CMake\bin\cmake.exe" --build . --target all
Scanning dependencies of target svgpp_agg_render
[  0%] Building CXX object demo/render/CMakeFiles/svgpp_agg_render.dir/F_/Git/svgpp/third_party/agg/src/agg_curves.cpp.obj
[  0%] Building CXX object demo/render/CMakeFiles/svgpp_agg_render.dir/F_/Git/svgpp/third_party/agg/src/agg_trans_affine.cpp.obj
[  1%] Building CXX object demo/render/CMakeFiles/svgpp_agg_render.dir/F_/Git/svgpp/third_party/agg/src/agg_vcgen_dash.cpp.obj
[  1%] Building CXX object demo/render/CMakeFiles/svgpp_agg_render.dir/F_/Git/svgpp/third_party/agg/src/agg_vcgen_stroke.cpp.obj
[  2%] Building CXX object demo/render/CMakeFiles/svgpp_agg_render.dir/svgpp_render.cpp.obj
C:/Qt/Qt5.12.1/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\svgpp_agg_render.dir\svgpp_render.cpp.obj: too many sections (70882)
C:\Users\ADMINI~1\AppData\Local\Temp\ccSYhzrf.s: Assembler messages:
C:\Users\ADMINI~1\AppData\Local\Temp\ccSYhzrf.s: Fatal error: can't write 67 bytes to section .text of CMakeFiles\svgpp_agg_render.dir\svgpp_render.cpp.obj: 'File too big'
C:/Qt/Qt5.12.1/Tools/mingw730_64/bin/../lib/gcc/x86_64-w64-mingw32/7.3.0/../../../../x86_64-w64-mingw32/bin/as.exe: CMakeFiles\svgpp_agg_render.dir\svgpp_render.cpp.obj: too many sections (70882)
C:\Users\ADMINI~1\AppData\Local\Temp\ccSYhzrf.s: Fatal error: can't close CMakeFiles\svgpp_agg_render.dir\svgpp_render.cpp.obj: File too big
mingw32-make.exe[2]: *** [demo\render\CMakeFiles\svgpp_agg_render.dir\build.make:119: demo/render/CMakeFiles/svgpp_agg_render.dir/svgpp_render.cpp.obj] Error 1
mingw32-make.exe[1]: *** [CMakeFiles\Makefile2:103: demo/render/CMakeFiles/svgpp_agg_render.dir/all] Error 2
mingw32-make.exe: *** [Makefile:83: all] Error 2
08:46:23: The process "C:\Program Files\CMake\bin\cmake.exe" exited with code 2.
Error while building/deploying project svgpp (kit: Desktop Qt 5.12.1 MinGW 64-bit)
When executing step "CMake Build"
08:46:23: Elapsed time: 01:02.`

Qt5.12.1
MinGW 4.2.1

**Comment by svgpp** [comment]
I've googled [a solution](https://stackoverflow.com/questions/16596876/object-file-has-too-many-sections). It it helps you may wish to commit it somewhere around https://github.com/svgpp/svgpp/blob/master/src/demo/render/CMakeLists.txt#L15 under GCC condition.

**Comment by omortie** [comment]
I tried to set -mbig-obj flags for linker, compiler and assembler for MinGW but non of them worked unfortunately, I will continue searching for that
