### ISSUE TITLE
SVGPP not compatible with boost 1.71.0

### ISSUE THREAD

**Issue by fhw72** [svgpp/svgpp#79]
My project using svgpp fails to compile if boost is upgraded from 1.70 to 1.71.

Errors occured:

d:\_proj\netlister\external\svgpp\include\svgpp\policy\value_events.hpp(22): error C2039: 'set': is not a member of 'LayoutContext::BaseContext'

Compiler used: Visual Studio 2017

**Comment by svgpp** [comment]
Looks like Boost.Parameter was broken in 1.71. I've [reported issue](https://github.com/boostorg/parameter/issues/91) to Boost.Parameter repo but haven't got any response.

**Comment by fhw72** [comment]
Still no fix in boost 1.72

**Comment by gladk** [comment]
Debian switched to Boost 1.71 and now has this problem as well. [#960426](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960426)

It is release-critical bug in Debian and there is a risk to get package dropped from the archive.
