### ISSUE TITLE
Does your library support SVG rendering and manipulating?

### ISSUE THREAD

**Issue by Nizarazo** [svgpp/svgpp#83]
Meaning user can click on SVG object and it will respond such as rotating or moving ?

**Comment by svgpp** [comment]
Hi,
No, svgpp is focused on just parsing SVG.

**Comment by Nizarazo** [comment]
Thank you for your response.
Do you know C++ tool that can manipulate SVG? 
or a tool that can parse and manipulate SVG?

**Comment by svgpp** [comment]
This information may be outdated, but there were no production grade C++ libraries when I started svgpp. I'd rather use some other language if possible (say, Batik library on Java). The other option it to cut out SVG part of some open-sourced browser which is pretty large amount of work.
