### ISSUE TITLE
There is a suggestion to improve demo

### ISSUE THREAD

**Issue by Fogrunner** [svgpp/svgpp#85]
Hello. 

First of all, thank you for sharing nice library.
I am really using this library very well.

Unfortunately, i have encountered an issue today. 

My application is using GDI Plus with c++.
So, i implemented it by referring to your demonstration.

The below code has the problem.

```
void PathStorage::path_close_subpath()
{
	if (!path_types_.empty())
	{ 
		path_types_.back() |= Gdiplus::PathPointTypeCloseSubpath;
	}
}

```

I recommand to change the code as like below.

```
void PathStorage::path_close_subpath()
{
       if (!path_types_.empty())
       {
	        if (path_types_.back() == 0)
		{
			path_points_.pop_back();
			path_types_.pop_back();
		}
		else
		{
			path_types_.back() |= Gdiplus::PathPointTypeCloseSubpath;
		}
	}
}

```

Because, GDI Plus does not allow to moving position with closing flag.

For example:
`M281 321z` is not a problem on SVG sentence.
By contrast, GDI Plus path will be not rendered.

**Comment by svgpp** [comment]
Applied your fix. Thank you.
