### ISSUE TITLE
Access attributes from non-svg namespaces? 

### ISSUE THREAD

**Issue by cglzhng** [svgpp/svgpp#86]
I noticed that svgpp skips attributes from non-svg namespaces: #24 
Is it possible to access these as well? Can be as just a string.

**Comment by svgpp** [comment]
If you replace factory::context::on_stack with factory::context::on_stack_with_xml_element another parameter will be passed to context constructor - XML element. This way you'll be able to query raw XML element for any attribute or non-SVG child elements etc using interface provided by your XML parser.

**Comment by cglzhng** [comment]
Thanks.
I was trying to follow sample01e to create child contexts for this reason.
But I noticed that the file doesn't compile. It gives this error:
```
include/svgpp/include/svgpp/policy/value_events.hpp:23:13: error: ‘class BaseContext’ has no member named ‘set’
   23 |     context.set(tag, args...);
      |     ~~~~~~~~^~~
```

**Comment by cglzhng** [comment]
Right, I see #79 now. Is this the same problem?

**Comment by svgpp** [comment]
You may try with Boost 1.70. No need to install, just unpack it somewhere and pass this path to CMake. Something like `cmake -DBOOST_ROOT=path`.
