### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by sanctorium** [svgpp/svgpp#87]
I am receiving some errors compiling svgpp (when building another library that uses svgpp).

First it was giving me some error about implicitly deleting boost::noncopyable because it would form an invalid constructor/function. Sorry I don't remember exactly and I didn't write down that error. 

So I pulled the last version of svgpp from the repository. And it now gives this error.

Maybe someone can shed some light. Thanks in advance.

/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/external/svgpp/include/svgpp/policy/value_events.hpp:23:5: error: no matching function for call to ‘Canvas::set(svgpp::tag::attribute::fill&, const int&, const svgpp::tag::skip_icc_color&)’
   23 |     context.set(tag, args...);
      |     ^~~~~~~
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:36:10: note: candidate: ‘void Stylable::set(svgpp::tag::attribute::stroke_width, float)’
   36 |     void set(tag::attribute::stroke_width, float val) { stroke_width = val; }
      |          ^~~
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:36:10: note:   candidate expects 2 arguments, 3 provided
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:37:10: note: candidate: ‘void Stylable::set(svgpp::tag::attribute::stroke, svgpp::tag::value::none)’
   37 |     void set(tag::attribute::stroke, tag::value::none) { stroke_paint = tag::value::none(); }
      |          ^~~
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:37:10: note:   candidate expects 2 arguments, 3 provided
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:38:10: note: candidate: ‘void Stylable::set(svgpp::tag::attribute::stroke, svgpp::tag::value::currentColor)’
   38 |     void set(tag::attribute::stroke, tag::value::currentColor) { stroke_paint = tag::value::currentColor(); }
      |          ^~~
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:38:10: note:   candidate expects 2 arguments, 3 provided
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:39:10: note: candidate: ‘void Stylable::set(svgpp::tag::attribute::stroke, std::experimental::io2d::v1::rgba_color, svgpp::tag::skip_icc_color)’
   39 |     void set(tag::attribute::stroke, rgba_color color, tag::skip_icc_color = tag::skip_icc_color()) { stroke_paint = color; }
      |          ^~~
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:39:14: note:   no known conversion for argument 1 from ‘svgpp::tag::attribute::fill’ to ‘svgpp::tag::attribute::stroke’
   39 |     void set(tag::attribute::stroke, rgba_color color, tag::skip_icc_color = tag::skip_icc_color()) { stroke_paint = color; }
      |              ^~~~~~~~~~~~~~~~~~~~~~
/home/jm/projects/P0267_RefImpl/P0267_RefImpl/Samples/svg/svg.cpp:41:10: note: candidate: ‘template<class IRI> void Stylable::set(svgpp::tag::attribute::stroke, const IRI&)’
   41 |     void set(tag::attribute::stroke /*tag*/, IRI const & /*iri*/) { throw std::runtime_error("Non-local references aren't supported"); }
      |          ^~~

**Comment by svgpp** [comment]
First of all check if you're using Boost 1.71/1.72, they have a bug in Boost.Parameter. See #79.

**Comment by sanctorium** [comment]
Hello,

Thank you Oleg.

Yes, I have Boost 1.72.0. And I think it the same bug in Boost (#79).

I am not very knowledable of Github etiquete. Do you want me to close the issue in svgpp?

Thank you again for the help.


José M. Otero R.

________________________________

Computer Scientist.

Master of Business Administration.

________________________________
De: Oleg Maximenko <notifications@github.com>
Enviado: jueves, 2 de abril de 2020 7:57 a. m.
Para: svgpp/svgpp <svgpp@noreply.github.com>
Cc: sanctorium <otero_jose@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [svgpp/svgpp] Compiling error (#87)


First of all check if you're using Boost 1.71/1.72, they have a bug in Boost.Parameter. See #79<https://github.com/svgpp/svgpp/issues/79>.

**Comment by svgpp** [comment]
I hope you'll be able to use Boost 1.69. svgpp is header-only library so you may just unpack Boost 1.69 somewhere and add this path to includes for the cpp's that use svgpp.
No worry about issue.

**Comment by sanctorium** [comment]
Just to confirm.

I just downloaded Boost 1.69 and compiled svgpp against it without any problems.

So this is solved. Thanks again.
