### ISSUE TITLE
Does SVGPP support animation?

### ISSUE THREAD

**Issue by jetlee2018** [svgpp/svgpp#89]
Does SVGP support parsing SVG animation, such as SMIL format?

Thanks!
Jie

**Comment by svgpp** [comment]
Only partially. I've skipped implementation of complex attributes such as `begin`, `end`, `keyTimes`, `keySplines` etc. 
I'd say animation parsing fits svgpp well, but it requires a little more efforts.
How it looks now you may see here - https://github.com/svgpp/svgpp/blob/master/src/samples/sample_animation.cpp
