### ISSUE TITLE
How to handle image element?

### ISSUE THREAD

**Issue by oneminute** [svgpp/svgpp#91]
There's no example about handling image element. Would you give an example?

**Comment by svgpp** [comment]
I think it should be viewport handling as described [here](http://svgpp.org/lesson01.html#handling-viewports) and `href` handling like [this](https://github.com/svgpp/svgpp/blob/a33934adf6c4105f668f4348f2fa0eac72b46328/src/samples/sample01e.cpp#L81).

**Comment by oneminute** [comment]
I'll have a try.
Thanks.
