### ISSUE TITLE
error C2589: '(': illegal token on right side of '::'

### ISSUE THREAD

**Issue by KochC** [svgpp/svgpp#93]
When following the first example I get the following error.
The code is basically exactly like `svgpp/src/samples/sample01a.cpp`
```
svgpp/adapter/rect.hpp(97): error C2589: '(': illegal token on right side of '::'
```

**Comment by svgpp** [comment]
https://stackoverflow.com/questions/2561368/illegal-token-on-right-side-of
`#define NOMINMAX` should help.

**Comment by KochC** [comment]
The issue was basically that I had all my code in a header file. Finally worked by putting the implementation, as it should be, in the `cpp` file. Works even without the `#define NOMINMAX`.
