### ISSUE TITLE
libxml2 freeing xmlChar* before sending to context

### ISSUE THREAD

**Issue by simonxeko** [svgpp/svgpp#95]
Thanks for making this amazing library.

I came across a bug when document_traversal.hpp:239
```
if (xml_policy_t::is_text(xml_child_element))
      {
        typename xml_policy_t::element_text_type text = xml_policy_t::get_text(xml_child_element);
        text_events_policy::set_text(context, xml_policy_t::get_string_range(text));
      }
```
called xml_policy_t::get_text in ​policy/xml/libxml2.hpp:227
```
static element_text_type get_text(iterator_type xml_element) {
   ​return detail::libxml_string_ptr(
     ​xmlNodeListGetString(xml_element->doc, xml_element, 1)).get_range();
 ​}
```

The **detail::libxml_string_ptr** will be deleted after leaving the **get_text** function, which called **xmlFree** on the string pointer returned by **xmlNodeListGetString**, then **text_events_policy::set_text** get a char range points to a freed pointer, making the behavior unpredictable.

Haven't read the full code but I guess if we change the element_text_type to detail::libxml_string_ptr, and modify get_string_range to accept detail::libxml_string_ptr, then the deconstructors could be called correctly.

**Comment by svgpp** [comment]
Hi, thank you for reaching me with this issue. Your proposed solution seems absolutely valid (it is similar to attribute_iterator:: get_value and it should be this way). Can you please help me with such PR if you have compilation with libxml already at hands?
